name: index.js

on:
  push:
    branches:
      - main
  schedule:   
    - cron: '30 7 * * *' 

jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
           
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got
          npm install tough-cookie         
          node ./index.js

